# Generated by Django 5.1.7 on 2025-04-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('is_copyright', models.IntegerField(blank=True, db_column='is_Copyright', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('namemp3', models.CharField(max_length=200)),
                ('listen', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tracks',
                'managed': False,
            },
        ),
    ]
