# Generated by Django 5.1.7 on 2025-04-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('popularity_score', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('gener', models.CharField(blank=True, max_length=255, null=True)),
                ('follower', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'artists',
                'managed': False,
            },
        ),
    ]
